config/routes.rb
Shidfolio::Application.routes.draw do
  root :to => "home#index"

  resources :home, :only => :index
  resources :cv, :only => :index
  resources :inad, :only => :index
  resources :siers, :only => :index
  resources :spear, :only => :index
  resources :capdc, :only => :index
  resources :ownlan, :only => :index
  resources :cpghost, :only => :index

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/capdc_controller.rb
class CapdcController < ApplicationController
  def index
    respond_to do |format|
	     format.html # index.html.erb
	     format.json { render json: @homes }
    end
  end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
	def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

end

app/controllers/inad_controller.rb
class InadController < ApplicationController
  def index
    respond_to do |format|
	     format.html # index.html.erb
	     format.json { render json: @homes }
    end
  end
end

app/controllers/siers_controller.rb
class SiersController < ApplicationController
  def index
    respond_to do |format|
	     format.html # index.html.erb
	     format.json { render json: @homes }
    end
  end
end

app/controllers/spear_controller.rb
class SpearController < ApplicationController
  def index
    respond_to do |format|
	     format.html # index.html.erb
	     format.json { render json: @homes }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capdc_helper.rb
module CapdcHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cp_ghost_helper.rb
module CpGhostHelper
end

app/helpers/cpghost_helper.rb
module CpghostHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inad_helper.rb
module InadHelper
end

app/helpers/ownlan_helper.rb
module OwnlanHelper
end

app/helpers/siers_helper.rb
module SiersHelper
end

app/helpers/spear_helper.rb
module SpearHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Shid'Folio
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    div class="navbar navbar-fixed-top"
      div class="navbar-inner"
        div class="container"
          a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="brand" href="#"
            ' Shid'Folio
          div class="nav-collapse"
            ul class="nav"
              li
                = link_to "Accueil", root_path
              li
                = link_to "Curriculum Vitae", cv_index_path
              li
                = link_to "Contactez-Moi", contact_path
            ul class="nav pull-right"
              a class="brand" Mes projets
              li
                = link_to "INAD", inad_index_path
              li
                = link_to "SPEAR", spear_index_path
              li
                = link_to "SIERS", siers_path
              li
                = link_to "CAPDC", capdc_index_path
              li
                = link_to "OwnLan", ownlan_index_path
              li
                = link_to "CP-Ghost", cpghost_index_path
    div class="container"
      div class="row"
        - if controller_name.classify == "Home" || controller_name.classify == "Cv"
	        div class="span12"
	          = yield
        - else
        	div class="span9"
	          = yield
        	div class="span3"
          	h3 A propos
            = image_tag('sidney-sissaoui.png', :border => 0, :width => "9%", :align => "left")
          	p align="justify" Etudiant en troisième année d'informatique, je suis un développeur travaillant essentiellement sous Ruby. Je m'intéresse à la veille technologique spécialement dans le domaine de la sécurité des réseaux wifi. Comme autres hobbies, je pratique le Muay Thai, joue au Jeu De Go, et suis friand de la culture Japonaise (Animation, Musique...)